### ISSUE TITLE
update gitignore

### ISSUE THREAD

**Issue by kristinmarshall-NOAA** [nissandjac/PacifichakeMSE#1]
Can we update the gitignore file to include Rstudio files: 

.Rproj.user/

More broadly, it might be helpful to use a template for the gitignore (R, maybe C++) to avoid similar issues in the future?
see https://docs.ropensci.org/gitignore/

**Comment by nissandjac** [comment]
Updated the gitingore file + some selectivity changes. Will look into a more general template later. 

There might be some issues with the model now, double checking and pushing fixes today.
