### ISSUE TITLE
missing run_multiple_MSEs_climate

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nissandjac/PacifichakeMSE#2]
I tried to re-run some of the scenarios to get the more detailed output as discussed yesterday, which worked fine for the HCR and movement scenarios, but the climate scenario quit after the first scenario with 
```
Error in run_multiple_MSEs_climate(simyears = simyears, seeds = seeds[i],  : 
  could not find function "run_multiple_MSEs_climate"
```
Is the fix as simple as changing `run_multiple_MSEs_climate` to `run_multiple_MSEs` on the following two lines?
https://github.com/nissandjac/PacifichakeMSE/blob/2ee85727b948418e2089647743c1996793f0d37c/Spatial%20MSE/run_MSE_climate.R#L64
https://github.com/nissandjac/PacifichakeMSE/blob/2ee85727b948418e2089647743c1996793f0d37c/Spatial%20MSE/run_MSE_climate.R#L89

**Comment by nissandjac** [comment]
Yes!
I removed the _climate file, and made 0 movement standard in the MSE run file. Just pushed the changes so it should be working again
