### ISSUE TITLE
run_MSE_selectivity.R not currently working

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nissandjac/PacifichakeMSE#3]
Error appeared as below when re-running different scenarios to get additional output. This isn't a high priority to fix, just noting the issue for future reference.

```
> source('run_MSE_selectivity.R')
make: Nothing to be done for 'all'.
Some stats skipped because the .par file not found:
    
warning.sso file not found
Loading required package: ggplot2
Error in if (df$flag_sel[yr] == 1) { : argument is of length zero
```

**Comment by nissandjac** [comment]
I've been redoing some indexing, which is causing some errors. Fixing them now, and pushing after

**Comment by nissandjac** [comment]
Pushed changes now, and should be working. 
Removed the file that called 'load_data_parameters_future, and incorporated it's utility into the regular 'load_data_parameters', which now takes an additional input 'yr_future', if the user want to add additional simulated years to the OM
