### ISSUE TITLE
Chris trying to run the code

### ISSUE THREAD

**Issue by cgrandin** [nissandjac/PacifichakeMSE#4]

**Comment by cgrandin** [comment]
What I have done:

1.  Cloned Repo
2. Installed/built all dependencies (already had them anyway)
3. source("run_mse_all.R") in the Spatial MSE directory

It's running, I will report back here when/if it breaks. Maybe I was running the Hake SAM before when it broke

**Comment by nissandjac** [comment]
Ok let me know if something is not working

**Comment by cgrandin** [comment]
After hours (I'm not sure how many as it was running overnight) this error was waiting for me this morning:

```
 Error in run.agebased.true.catch(df) : 
Catch exceeds available biomass in year: 1966  and season 4 area 2
Catch exceeds available biomass in year: 1967  and season 4 area 2
Catch exceeds available biomass in year: 1968  and season 4 area 2
Catch exceeds available biomass in year: 1969  and season 4 area 2
Catch exceeds available biomass in year: 1970  and season 4 area 2
Catch exceeds available biomass in year: 1971  and season 4 area 2
Catch exceeds available biomass in year: 1972  and season 4 area 2
Catch exceeds available biomass in year: 1973  and season 4 area 2
Catch exceeds available biomass in year: 1974  and season 4 area 2
Catch exceeds available biomass in year: 1975  and season 4 area 2
Catch exceeds available biomass in year: 1976  and season 4 area 2
Catch exceeds available biomass in year: 1977  and season 4 area 2
Catch exceeds available biomass in year: 1978  and season 4 area 2
Catch exceeds available biomass in year: 1979  and season 4 area 2
Catch exceeds available biomass in year: 1980  and season 4 area 2 
```
My answer would be changing that to a warning instead of a stop but I'm unsure of the implications of that later.
What do you think?

**Comment by nissandjac** [comment]
Hi Chris,
which script have you been running, and at what index did it stop? 
That error code is set in place, so if the fish it not there it stops. It doesn't do that in the future, so you must have changed something in the operating model. If I can recreate it, perhaps I can explain what happened

**Comment by cgrandin** [comment]
Hey Nis..

I just did a clone then entered the `Spatial MSE` directory and ran:

```
source("run_mse_all.R")
```

I started completely clean and synced to the GitHub repository, without any local changes.
Is that the right script?

**Comment by nissandjac** [comment]
Okay, I just double checked it. This is actually not a bug, but a feature! 

The movement rates that it's currently using in the last simulation in the code (i.e., movement 3), are not possible given the historical catch. You  have already run the 3 harvest control rules scenarios, and the two movement scenarios before, and saveed it to your disc (so the time has not been in vain). 

You could try to change the two movement parameters  in this line 

`df <- load_data_seasons(nseason = 4, nspace = 2,movemaxinit = 0.6, movefiftyinit = 4) # Prepare data for operating model`

and make sure that the 'test' and run 

`test <- run.agebased.true.catch(df)`

and make sure it runs before starting the whole MSE

**Comment by nissandjac** [comment]
I haven't used that particular file in a while, and that is probably the reason the parameters are a bit outdated, with  some of the newer stuff that has been implemented

**Comment by nissandjac** [comment]
Looking again, I think the issue is occurring now because I changed slightly how the fisheries operate between seasons. Each countries total catch in a season is divided by a fraction of the total catch, and last week we updated that to be the same as the average of the ten last years (I'm not sure which fleets included, Ian would know that). 

The errors with the old movement values seem to mainly have issues with the early period (1965:1990), so perhaps the fisheries worked differently back then? I don't know.

**Comment by cgrandin** [comment]
OK, thanks Nis, I will try again and see what happens. You said you haven't used that script in awhile, which script are you running mostly?

**Comment by iantaylor-NOAA** [comment]
The catch by month data that I was using to calculate averages only went back to the 1990s (see figs attached to Asana issue here https://app.asana.com/0/search/1145606217991961/604905773257490). 

The seasonality probably was different in the early period but we may not be able to figure that out. And regardless that shouldn't have much impact on the forecast period which is the focus of the MSE as long as the model can get through the early years without running out of fish.

**Comment by nissandjac** [comment]
It depends on the scenario. 

run_MSE_xxxx runs the differnent ones I showed at the august meeting.
